#!/usr/bin/env bash
# Open and merge N trivial PRs against the current repo.
# Usage: ./scripts/pr-flow.sh [count] [base-branch]
set -euo pipefail

COUNT="${1:-1}"
BASE="${2:-main}"
COAUTHOR="${COAUTHOR:-}"

git switch "$BASE"
git pull --ff-only

for ((n = 1; n <= COUNT; n++)); do
  branch="pr-flow-$(date +%s)-$n"
  git switch -c "$branch"

  printf '%s\n' "$branch" >> CHANGELOG.md
  git add CHANGELOG.md

  if [[ -n "$COAUTHOR" ]]; then
    git commit -m "Change from $branch" -m "" -m "Co-authored-by: $COAUTHOR"
  else
    git commit -m "Change from $branch"
  fi

  git push -u origin "$branch"
  gh pr create --title "Change from $branch" \
    --body "Generated by scripts/pr-flow.sh" --base "$BASE" --head "$branch"
  gh pr merge "$branch" --merge --delete-branch

  git switch "$BASE"
  git pull --ff-only
done
